#!/bin/sh
. /etc/rc.common

StartService ()
{
    ConsoleMessage "Running SpoofMAC script."
    spoof-mac randomize en0
}

StopService ()
{
    return 0
}

RestartService ()
{
    return 0
}

RunService "$1"